
// Incluir produto
POST http://127.0.0.1:5000/produto
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
  "descricao" : "Tapioca",
  "unidade"   : "Unid",
  "quantidade" : 5,
  "preco_real" : 4.70,
  "preco_dolar": 0.0
}
// Utiliza-se obrigatoriamente no início da linha os simbolos: ###
// para separar uma requisção da outra. 
###

// Alterar produto pelo id
PUT http://127.0.0.1:5000/produto
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
    "descricao" : "Acai",
    "id": 2,
    "unidade"   : "Litro",
    "quantidade" : 10,
    "preco_real" : 12.50,
    "preco_dolar": 0.0
}

// Utiliza-se obrigatoriamente no início da linha os simbolos: ###
// para separar uma requisção da outra. 
###

// Alterar o preco dolar do produto pelo id
PUT http://127.0.0.1:5000/produto/preco_dolar
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
  "id": 1,
  "preco_dolar": 350.0
}
// Utiliza-se obrigatoriamente no início da linha os simbolos: ###
// para separar uma requisção da outra. 
###

###
// Listar todos os produtos em ordem alfabética pela descricao
GET http://127.0.0.1:5000/produto
Content-Type: application/json
###

// Obter produto pelo ID
// http://127.0.0.1:5000/produto/id
GET http://127.0.0.1:5000/produto/3
Content-Type: application/json
###

// Deletar produto pelo ID
// http://127.0.0.1:5000/produto/id
DELETE http://127.0.0.1:5000/produto/1
Content-Type: application/json
###
